apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
  labels:
    app: django-messaging
spec:
  type: ClusterIP
  selector:
    app: django-messaging
    version: blue  # Initially points to blue version
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
---
# Additional service for green version (for testing/verification)
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service-green
  labels:
    app: django-messaging
spec:
  type: ClusterIP
  selector:
    app: django-messaging
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
